[project]
name = "x-tokens"
version = "0.1.0"
description = "An efficient, lightweight, and easy-to-use LLM inference system"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
benchmark = ["datasets>=3.0"]

[tool.setuptools]
package-dir = {"" = "benchmarks"}
packages = [
  "test_serve",
  "test_serve.cli",
  "test_serve.dataset",
  "test_serve.lib",
  "test_serve.tests",
]
